sudo: required
services: 
  - docker

before_install:
  - docker build -t mayurijoshi3108/docker-react -f Dockerfile.dev .

script:
  - docker run mayurijoshi3108/docker-react npm run test -- --coverage       
